name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run prerelease
